POST http://localhost:3000/api/todos
Content-Type: application/json

{
    "title": "learn coding",
    "description": "better learn fucking coding"
}

###

POST http://localhost:3000/api/auth/sign-in/email
Content-Type: application/json

{
    "email": "rommelbon100@gmail.com",
    "password": "password123"
}

###

